version: "3.9"
volumes:
    scrumhub-database-volume: {}
services:
    frontend:
        container_name: frontend
        build: ./scrumhubfrontend
        ports:
            - "3000:3000"
            - "5000:5000"
    database:
        container_name: database
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        volumes:
            - scrumhub-database-volume:/var/opt/mssql
    backend:
        container_name: backend
        build: .
        ports:
            - "5033:5033"
        depends_on:
            - database