import { NavigateFunction } from "react-router";
import * as Actions from "../../appstate/actions";
import { store } from "../../appstate/store";
import { clearProjectLocalStorage, setLoginStateLocalStorage } from "./commonFunctions";
import { loginDataError } from "./commonInitValues";
import { ILoginData } from "./commonInterfaces";

/**
 * Handles user login for the given token returned from GitHub
 * @param {String} token Token generated by GitHub for the current user
 * @param {NavigateFunction} navigate Function for changing the route 
 * @param {React.Dispatch<React.SetStateAction<ILoginData>>} setData Action for updating the state of Login data
 */
export function handleLogin(token: string, navigate: NavigateFunction, setData: React.Dispatch<React.SetStateAction<ILoginData>>): void {
    clearProjectLocalStorage();
    store.dispatch(
        Actions.getCurrentUserThunk({
            token: token,
        })
    ).then((response: any) => {
        if (response.payload && response.payload.code !== 0) {
            store.dispatch(Actions.login({ token: token, isLoggedIn: true }));
            setLoginStateLocalStorage(token);
            navigate("/", { replace: true });
        } else {
            setData(loginDataError);
        }
    });
}
/**
 * Renders routes for the breadcrumb component
 * @returns renderedRoutes
 */
export function ItemRender(route: any, params: any[], routes: any[], paths: string[]): JSX.Element {
    return (<span key={route.path}>{(route.icon ? route.icon : "")}{" " + route.breadcrumbName}</span>)
  }
